//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AccuStudio.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_STUDIOFILE                  103
#define IDR_MAINFRAME                   128
#define IDR_ACCUSTTYPE                  129
#define IDD_TREE_CONTAINER              130
#define IDR_ACCUSTPTYPE                 130
#define IDD_NEW_PROJECT                 132
#define IDD_PROJECTFILES                134
#define IDD_GRAMSETNAME                 135
#define IDD_RESULTS_CONTAINER           136
#define IDD_GRAMMAR_WIZARD              138
#define IDD_FINDDLG                     139
#define IDD_GOTO                        140
#define IDD_OBJECT_WIZARD               141
#define IDD_GRAMMAR_EXERSIZER           142
#define IDD_SHOWNBEST                   143
#define SETTINGS_DLG                    147
#define IDD_PREREC                      150
#define IDD_SELTEMPLATE                 152
#define IDC_TREE_CONTROL                1000
#define IDC_PROJ_LOCATION               1002
#define IDC_PROJ_RESLOC                 1004
#define IDC_LOCSEARCH                   1006
#define IDC_RESSEARCH                   1007
#define IDC_GRAMMARSETLIST              1027
#define IDC_NAME                        1029
#define IDC_FILELIST                    1032
#define IDC_RES_LIST                    1033
#define IDC_DLG                         1034
#define IDC_GRAMNAME                    1035
#define IDC_CONTROL                     1036
#define IDC_CONTROLNAME                 1037
#define IDC_FOCUS_PROMPT                1038
#define IDC_DATA_ENTRY_PROMPT           1039
#define IDC_BASELINE_RULE               1040
#define IDC_DESCRIPTION                 1042
#define IDC_RECPHRASELIST_TEXT          1043
#define IDC_DATA_ENTRY_PROMPT_TEXT      1044
#define IDC_BASELINE_GRAMMAR_TEXT       1045
#define IDC_PHRASE_LIST                 1046
#define IDC_GRAMMARSET                  1047
#define IDC_NEXT_CONTROL                1048
#define IDC_CONTROLNAME_TEXT            1049
#define IDC_BASELINE_GRAMMAR            1050
#define IDC_BUILD                       1052
#define IDC_ATTACH                      1053
#define IDC_DLG_TEXT                    1055
#define IDC_GRAMNAME_TEXT               1056
#define IDC_CONTROL_TEXT                1057
#define IDC_CMDPROMPT_TEXT              1058
#define IDC_ADD                         1059
#define IDC_SUBTRACT                    1060
#define IDC_DEADD                       1061
#define IDC_FINDSTR                     1062
#define IDB_PREREC                      1062
#define IDC_WHOLEWORD                   1063
#define IDB_PREREC2                     1063
#define IDC_MATCHCASE                   1064
#define IDC_LINENUM                     1066
#define IDC_CANDIDATE_GRAMMAR_TEXT      1069
#define IDC_CANDIDATE                   1070
#define IDC_SEMANTIC_CALLS              1071
#define IDC_ABOUT                       1072
#define IDC_CANDIDATE_GRAMMAR_TEXT2     1072
#define IDC_REC_RESULTS                 1073
#define IDC_RECOGNIZE                   1074
#define IDC_NBESTCANDIDATE              1075
#define IDC_CHECK1                      1079
#define IDC_ENABLE_ACTIVATION           1079
#define IDC_VOICEPROMPT                 1079
#define IDC_NEWLOGIC                    1079
#define IDC_VIAVOICE_REC                1080
#define IDC_NUANCE_REC                  1081
#define IDC_WAVECAPTURE                 1081
#define IDC_NUANCE_REC2                 1082
#define IDC_FONIX_REC                   1082
#define IDC_ACTIONS                     1082
#define IDC_PLAYWAV                     1083
#define IDC_CHECK2                      1084
#define IDC_DYNAMIC                     1084
#define IDC_LANGUAGE                    1085
#define IDC_COMBO2                      1086
#define IDC_MODEL                       1086
#define IDC_COMBO1                      1087
#define IDC_SELTEMPLATE                 1087
#define IDC_CONTROL_COMBO               1087
#define IDC_MAJOR                       1088
#define IDC_MINOR                       1089
#define IDC_MINOR2                      1090
#define IDC_SUB                         1090
#define IDC_PTT                         1090
#define IDC_RADIO2                      1091
#define IDC_AWL                         1091
#define ID_FILE_SAVE_PROJECT            32771
#define ID_FILE_CLOSE_PROJECT           32772
#define ID_VIEW_PROJECT                 32782
#define ID_PROJECT_SETTINGS             32785
#define ID_PROJECT_DEBUF                32786
#define ID_PROJECT_EXERCISEGRAMMAR      32787
#define ID_FILE_OPEN_PROJECT            32798
#define ID_PROJECT_ADD_GRAMMARSET       32799
#define ID_PROJECT_ADD_GRAMMAR          32800
#define ID_BUILD_BUILD_PROJECT          32801
#define ID_PROJECT_DEBUG                32802
#define ID_FILE_SAVEAS                  32805
#define ID_FILE_SAVEALL                 32806
#define ID_VIEW_GRAMMAR_WIZARD          32808
#define ID_FILE_NEW_PROJECT             32809
#define ID_PROJECT_ADDGRAMMARFILES      32810
#define ID_BUILD_BUILDFROMDEFINITIONFILE 32811
#define ID_VIEW_RESULTS                 32812
#define ID_EDIT_GOTO                    32814
#define ID_VIEW_OBJECTWIZARD            32815
#define ID_GRAMMAR_EXERCISE             32816
#define ID_TOOLS_ANALYSEHTML            32817
#define ID_GRAMMAR_BUILDLIBRARY         32818
#define ID_TOOLS_ANALYSEHTML32819       32819
#define ID_Menu                         32820
#define ID_TARGET_IBMVIAVOICE           32821
#define ID_TARGET_NUANCEVOCON3200       32822
#define ID_PROJECT_UPDATEPROJECTFROMRESOURCEFILE 32823
#define ID_Menu32824                    32824
#define ID_PROJECT_UPDATEPROJECTFROMRESOURCEFILE32825 32825
#define ID_PROJECT_ADDRESOURCESFROMRESOURCEFILE 32826
#define ID_Menu32827                    32827
#define ID_PROJECT_ADDRESOURCEFROMRESOURCEFILE 32828
#define ID_TOOLS                        32829
#define ID_TOOLS32830                   32830
#define ID_FILE_NEW_MENU                32831
#define ID_HELP_SEMANTICCODES           32834
#define ID_HELP_SEMANTICCODES32835      32835

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32836
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
